//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Performance.Test {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    
    
    public class WebTest1Coded : WebTest {
        
        public WebTest1Coded() {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request1.QueryStringParameters.Add("query", "ww", false, false);
            request1.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request1.QueryStringParameters.Add("rowheight", "20", false, false);
            request1.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request1.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request1.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request2.QueryStringParameters.Add("query", "www", false, false);
            request2.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request2.QueryStringParameters.Add("rowheight", "20", false, false);
            request2.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request2.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request2.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request3.QueryStringParameters.Add("query", "www.", false, false);
            request3.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request3.QueryStringParameters.Add("rowheight", "20", false, false);
            request3.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request3.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request3.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request4.QueryStringParameters.Add("query", "www.h", false, false);
            request4.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request4.QueryStringParameters.Add("rowheight", "20", false, false);
            request4.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request4.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request4.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request5.ThinkTime = 6;
            request5.QueryStringParameters.Add("query", "www.ht", false, false);
            request5.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request5.QueryStringParameters.Add("rowheight", "20", false, false);
            request5.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request5.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request5.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request6.QueryStringParameters.Add("query", "www.hdf", false, false);
            request6.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request6.QueryStringParameters.Add("rowheight", "20", false, false);
            request6.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request6.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request6.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request7.ThinkTime = 3;
            request7.QueryStringParameters.Add("query", "www.hdfc", false, false);
            request7.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request7.QueryStringParameters.Add("rowheight", "20", false, false);
            request7.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request7.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request7.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://www.bing.com/search");
            request8.QueryStringParameters.Add("q", "www.hdfcbank.com", false, false);
            request8.QueryStringParameters.Add("src", "IE-SearchBox", false, false);
            request8.QueryStringParameters.Add("FORM", "IESR02", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://www.bing.com/fd/ls/l");
            request9.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request9.QueryStringParameters.Add("IG", "BB23759912D042EA9449A89347BB9189", false, false);
            request9.QueryStringParameters.Add("Type", "Event.CPT", false, false);
            request9.QueryStringParameters.Add("DATA", "{%22pp%22:{%22S%22:%22L%22,%22FC%22:59,%22BC%22:236,%22SE%22:-1,%22TC%22:-1,%22H%" +
                    "22:369,%22BP%22:453,%22CT%22:462,%22IL%22:10},%22ad%22:[-1,-1,558,520,1089,2437," +
                    "1]}", false, false);
            request9.QueryStringParameters.Add("P", "SERP", false, false);
            request9.QueryStringParameters.Add("DA", "HK2", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://www.bing.com/fd/ls/lsp.aspx");
            request10.Method = "POST";
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request10.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request10Body = new StringHttpBody();
            request10Body.ContentType = "text/xml";
            request10Body.InsertByteOrderMark = false;
            request10Body.BodyString = @"<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>BB23759912D042EA9449A89347BB9189</IG><TS>1551796969805</TS><D><![CDATA[{id:9166,P:""7:1,5:1,15:lg,14:ku,13:ku,12:ku,11:6r,4:1,3:1,2:1,17:m8,16:m8,24:aa,8:6o,10:ko,9:6r"",S:""nav:0"",v:1.1,T:""CI.Perf"",FID:""CI"",Name:""PerfV2""}]]></D></E></Events><STS>1551796969805</STS></ClientInstRequest>";
            request10.Body = request10Body;
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://www.bing.com/images/sbi");
            request11.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request11.QueryStringParameters.Add("mmasync", "1", false, false);
            request11.QueryStringParameters.Add("ig", "BB23759912D042EA9449A89347BB9189", false, false);
            request11.QueryStringParameters.Add("iid", ".5056", false, false);
            request11.QueryStringParameters.Add("ptn", "Web", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://www.bing.com/fd/ls/l");
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request12.QueryStringParameters.Add("IG", "BB23759912D042EA9449A89347BB9189", false, false);
            request12.QueryStringParameters.Add("Type", "Event.PPT", false, false);
            request12.QueryStringParameters.Add("DATA", "{%22S%22:580,%22E%22:1292,%22T%22:0,%22I%22:0,%22N%22:{%22TP%22:{%22S%22:722,%22E" +
                    "%22:724,%22T%22:2}},%22M%22:{}}", false, false);
            request12.QueryStringParameters.Add("P", "SERP", false, false);
            request12.QueryStringParameters.Add("DA", "HK2", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://www.bing.com/fd/ls/lsp.aspx");
            request13.ThinkTime = 3;
            request13.Method = "POST";
            request13.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            StringHttpBody request13Body = new StringHttpBody();
            request13Body.ContentType = "text/xml";
            request13Body.InsertByteOrderMark = false;
            request13Body.BodyString = "<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>BB23759912D042EA9449A893" +
                "47BB9189</IG><TS>1551796970897</TS><D><![CDATA[[{\"T\":\"CI.BoxModel\",\"FID\":\"CI\",\"N" +
                "ame\":\"v2.8\",\"SV\":\"4\",\"P\":{\"C\":66,\"N\":1,\"I\":\"51d\",\"S\":\"T\",\"M\":\"V+L+M+MT+E+N+C+K+B" +
                "D\",\"T\":1903,\"K\":\"189+SPAN.ftrB+LI.b_algo+LI.b_ans+1vp+1vo+SERP,5022.1+SERP,5190." +
                "1+SERP,5103.1+DIV.rms_img rms_rmsanswersMultimediaVideoAnswer_Play rms_rmsanswer" +
                "sMultimediaVideoAnswer_Bundle+SERP,5498.1+IMG.rms_img+DIV.rms_img+www.bing.com+h" +
                "ttp+css+img+12s+1b7dfb88%2Fcc8437ad.js+script+1beceeda%2F3baa9af7.js+xmlhttprequ" +
                "est+12t+5983aa50%2Ff8c6dd44.js+4c7364c5%2F40e1b425.js+57013c47%2F1adb5dba.js+bab" +
                "57e12%2Fea8fe300.js+347afee2%2F33036ea1.js+76efe231%2Fc6376e53.js+e90431ed%2Fb2f" +
                "e50be.js+d5712f1a%2Fe58e5083.js+ef06908b%2F03502832.js+8bf5c256%2Fdb475c97.js+a3" +
                "9998e4%2F6798a322.js+b559b0ca%2Fc6f6e566.js+d488ec88%2F182800dc.js+10e+db8677a2%" +
                "2F0716c9f4.js+10l+57b92daf%2Fbf9758b4.js+10t+5a94fd03%2F421a0c09.js+110+7d221d55" +
                "%2Fee8d79e1.js+11c+1c2f626c%2Fc9969752.js+11k+16be2a34%2F6323ce42.js+11r+12c+12j" +
                "+13o+13s+13y+149+14r+14x+154+162+19k+19o\",\"F\":0},\"V\":\"b9/0/0/fz/ex/u9/3b/1/d/vis" +
                "ible/default+j9//////@4////+@0//////@5////\",\"L\":\"ba/0/NAV.b_scopebar/SERP,5016.1" +
                "/2s/27/rh/13/2/T/-1+ba/1/H1.b_logo//1m/g/s/10/4/T/-1+ba/2/DIV.b_searchboxForm//2" +
                "s/e/i0/14/3/T/-1+ba/3/DIV#id_h/@6/q1/a/48/1e/2/T/2+@0/3///nj//6q///T/+jg/4/SPAN." +
                "sb_count//3c/3o/3e/u/4/T/-1+jg/5/@1/SERP,5348.1/6q/3o/2q/u/4/T/-1+jg/6/@1/SERP,5" +
                "357.1/9g/3o/3i/u/4/T/-1+jg/7/@1/SERP,5361.1/cy/3o/2e/u/4/T/-1+jg/8/@2/SERP,5137." +
                "1/2s/4i/i0/ei/4/T/-1+jg/9/@2/@7/2s/j2/i0/9g/4/T/-1+jg/a/LI.b_ans b_mop/@8/2s/sk/" +
                "i0/7h/4/T/-1+jg/b/@2/SERP,5204.1/2s/103/i0/2s/4/T/-1+@0/b////102////T/+jg/c/@2/S" +
                "ERP,5218.1/2s/12x/i0/3a/4/T/-1+@0/c////12w////T/+jg/d/@2/SERP,5233.1/2s/169/i0/2" +
                "s/4/T/-1+@0/d////168////T/+jg/e/@2/SERP,5248.1/2s/193/i0/2s/4/T/-1+@0/e////192//" +
                "//T/+jg/f/@2/SERP,5261.1/2s/1bx/i0/2a/4/T/-1+@0/f////1bw////T/+jg/g/@2/SERP,5276" +
                ".1/2s/1e9/i0/3a/4/T/-1+@0/g////1e8////T/+jg/h/@2/SERP,5287.1/2s/1hl/i0/2a/4/T/-1" +
                "+@0/h////1hk////T/+jg/i/@2/SERP,5302.1/2s/1jx/i0/2s/4/T/-1+@0/i////1jw////T/+jg/" +
                "j/@3/SERP,5486.1/2s/1mr/i0/5i/4/T/-1+@0/j////1mq////T/+jg/k/LI.b_pag/SERP,5536.1" +
                "/2s/1sb/i0/2s/4/T/-1+@0/k////1sa////T/+jg/l/@3/@a/lw/4i/88/ka/4/T/-1+jg/m/FOOTER" +
                "#b_footer/SERP,5049.1/0/@4/u9/1c/1/T/-1+@0/m////@5////T/+ba/n/IMG//1m/g/mt/1q/5/" +
                "T/-1+@0/o/IMG#sbi_b//iw/o/k/k/7/T/2+@0/p/IMG.infbtnimg rms_img//0/0/0/0/9/T/2+@0" +
                "/q/IMG.clsbtnimg rms_img//0/0/0/0/9/T/2+@0/r/IMG.clsoptbtnimg rms_img//0/0/0/0/9" +
                "/T/2+@0/s/IMG.psticon rms_img//0/0/0/0/c/T/2+@0/t/IMG.tpicon rms_img//0/0/0/0/b/" +
                "T/2+@0/u/IMG.dpicon rms_img//0/0/0/0/c/T/2+ba/v/IMG#id_p/@6/0/0/0/0/4/T/2+jg/w/I" +
                "MG#emb337159D2/@7/3c/kx/5h/2s/l/T/2+jg/x/IMG#emb1282C1FE1/@7/eq/kx/5h/2s/l/T/2+j" +
                "g/y/IMG#emb20F67D2FE/@8/3c/u5/5f/30/c/T/-1+jg/z/@9/@8/3k/wr/7/8/e/T/-1+@0/z////w" +
                "q////T/+jg/10/IMG#emb34FDEA737/@8/8z/u5/5f/30/c/T/-1+jg/11/@9/@8/97/wr/7/8/e/T/-" +
                "1+@0/11////wq////T/+jg/12/IMG#emb428E37757/@8/em/u5/5f/30/c/T/-1+jg/13/@9/@8/eu/" +
                "wr/7/8/e/T/-1+@0/13////wq////T/+@0/14/@b/@a/mf/6f/32/32/b/T/-1+jg/15/@b/@a/mw/9r" +
                "/w/w/d/T/-1+jg/16/@b/@a/p4/9r/w/w/d/T/-1+jg/17/@b/@a/rc/9r/w/w/d/T/-1+jg/18/@c/@" +
                "a/mf/ia/23/23/c/T/-1+@0/19/@b/@a/mc/i7/6l/29/d/T/-1+jg/1a/@c/@a/os/ia/23/23/c/T/" +
                "-1+@0/1b/@b/@a/mj/i7/6l/29/d/T/-1+jg/1c/@c/@a/r5/ia/23/23/c/T/-1+@0/1d/@b/@a/mq/" +
                "i7/6l/29/d/T/-1\",\"E\":\"1ge/l/X/26/\",\"N\":\"-1/0///document//m8//1/-1/1/6o/6r/ko+a4/" +
                "1/n/@d/simg%2FSharedSpriteDesktopRewards_022118.png/@g/8/@e/a8/-1/a8/a8/a8/ad+ho" +
                "/2//@d/ead77415%2F3938fd08.png/@f/8/@e/hu/-1/hu/hu/hu/hx+jg/3//@d/61505d92%2F25d" +
                "df288.png/@f/6/@e/jj/-1/jj/jj/jj/jm+mj/4//@d/cpt/@g/3i/@e/ml/-1/ml/mm/-1/q2+mw/5" +
                "//@d/ls%2Flsp.aspx/@l/fv/@e/oi/-1/oi/ok/@h/@h+mz/6//@d/BingCore.Bundle/@j/10/@e/" +
                "nw/-1/nw/nw/nw/o0+q2/7/14/@d/th/@g/9/@e/q7/-1/q7/q7/q7/qb+q8/8/19/@d/th/@g/k/@e/" +
                "qk/-1/qk/qk/qk/qt+qm/9//@d/@i/@g/a/@e/qr/-1/qr/qr/qr/qw+qx/a//@d/@k/@g/4/@e/r1/-" +
                "1/r1/r1/r1/r2+r3/b//@d/@n/@g/4/@e/r7/-1/r7/r7/r7/r7+r9/c//@d/@o/@g/3/@e/rc/-1/rc" +
                "/rc/rc/rd+rd/d//@d/@p/@g/3/@e/rg/-1/rg/rg/rg/rh+rh/e//@d/@q/@g/4/@e/rl/-1/rl/rl/" +
                "rl/rm+rn/f//@d/@r/@g/5/@e/rs/-1/rs/rs/rs/rs+rt/g//@d/@s/@g/3/@e/rx/-1/rx/rx/rx/r" +
                "x+ry/h//@d/@t/@g/3/@e/s1/-1/s1/s1/s1/s2+s3/i//@d/@u/@g/3/@e/s6/-1/s6/s6/s6/s7+s7" +
                "/j//@d/@v/@g/3/@e/sa/-1/sa/sa/sa/sb+sb/k//@d/@w/@g/4/@e/sf/-1/sf/sf/sf/sf+sh/l//" +
                "@d/@x/@g/6/@e/sm/-1/sm/sm/sm/sn+so/m//@d/@y/@g/3/@e/sr/-1/sr/sr/sr/ss+st/n//@d/@" +
                "z/@g/3/@e/sw/-1/sw/sw/sw/sw+sy/o//@d/@11/@g/3/@e/t1/-1/t1/t1/t1/t1+t2/p//@d/@13/" +
                "@g/3/@e/t5/-1/t5/t5/t5/t6+t6/q//@d/@15/@g/3/@e/t9/-1/t9/t9/t9/ta+tb/r//@d/@17/@g" +
                "/3/@e/te/-1/te/te/te/tf+tg/s//@d/@19/@g/3/@e/tj/-1/tj/tj/tj/tk+tk/t//@d/@1b/@g/3" +
                "/@e/tn/-1/tn/tn/tn/to+tv/u//@d/@i/@j/4/@e/ty/-1/ty/ty/ty/tz+uc/v//@d/@k/@j/5/@e/" +
                "ug/-1/ug/ug/ug/uh+ul/w//@d/images%2Fsbi/@l/8j/@e/@m/-1/@m/@m/12u/135+uo/x//@d/@n" +
                "/@j/4/@e/us/-1/us/us/us/ut+uw/y//@d/@o/@j/3/@e/uz/-1/uz/uz/uz/v0+v4/z//@d/@p/@j/" +
                "4/@e/v8/-1/v8/v8/v8/v8+vj/10//@d/@q/@j/4/@e/vn/-1/vn/vn/vn/vn+w6/11//@d/@r/@j/4/" +
                "@e/w9/-1/w9/w9/w9/wa+x7/12//@d/@s/@j/5/@e/xb/-1/xb/xb/xb/xc+xv/13//@d/@t/@j/5/@e" +
                "/xz/-1/xz/xz/xz/y0+y8/14//@d/@u/@j/c/@e/yg/-1/yg/yg/yg/yk+yp/15//@d/@v/@j/5/@e/y" +
                "t/-1/yt/yt/yt/yu+yz/16//@d/@w/@j/6/@e/z5/-1/z5/z5/z5/z6+z9/17//@d/@x/@j/4/@e/zd/" +
                "-1/zd/zd/zd/ze+zi/18//@d/@y/@j/4/@e/zm/-1/zm/zm/zm/zn+10a/19//@d/@z/@j/4/@e/@10/" +
                "-1/@10/@10/@10/@10+10i/1a//@d/@11/@j/3/@e/@12/-1/@12/@12/@12/@12+10q/1b//@d/@13/" +
                "@j/3/@e/@14/-1/@14/@14/@14/@14+10y/1c//@d/@15/@j/3/@e/@16/-1/@16/@16/@16/111+119" +
                "/1d//@d/@17/@j/4/@e/@18/-1/@18/@18/@18/11d+11h/1e//@d/@19/@j/3/@e/@1a/-1/@1a/@1a" +
                "/@1a/11l+11o/1f//@d/@1b/@j/4/@e/@1c/-1/@1c/@1c/@1c/11s+129/1g/w/@d/th/@g/8/@e/@1" +
                "d/-1/@1d/@1d/@1d/12h+12d/1h/x/@d/th/@g/d/@e/@1e/-1/@1e/@1e/@1e/12q+13g/1i/o/@d/6" +
                "8e94a1b%2Fd7ffd2fd.svg/@g/9/@e/@1f/-1/@1f/@1f/@1f/13q+13p/1j/p/@d/b7460a1a%2Fcb3" +
                "dd66f.svg/@g/7/@e/@1g/-1/@1g/@1g/@1g/13w+13t/1k/q/@d/c4a64003%2F64c27dd3.svg/@g/" +
                "6/@e/@1h/-1/@1h/@1h/@1h/140+13z/1l/r/@d/e243f498%2F7f7111bf.svg/@g/k/@e/@1i/-1/@" +
                "1i/@1i/@1i/14k+14a/1m/s/@d/878ca0cd%2Fb83d57c0.svg/@g/j/@e/@1j/-1/@1j/@1j/@1j/14" +
                "u+14t/1n/t/@d/207638d1%2F7650a3a8.svg/@g/7/@e/@1k/-1/@1k/@1k/@1k/150+14y/1o/u/@d" +
                "/616df52f%2F976cbfb8.svg/@g/8/@e/@1l/-1/@1l/@1l/@1l/156+160/1p//@d/sbiwebcam/@g/" +
                "3k/@e/@1m/-1/@1m/@1m/-1/@1n+@1n/1q//@d/ppt/@g/4a/@e/@1o/-1/@1o/19p/-1/1du\"}]]]><" +
                "/D></E></Events><STS>1551796970897</STS></ClientInstRequest>";
            request13.Body = request13Body;
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://www.hdfcbank.com/");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://www2.bing.com/ipv6test/test");
            request15.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request15.QueryStringParameters.Add("FORM", "MONITR", false, false);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://www.bing.com/ipv6test/test");
            request16.ThinkTime = 2;
            request16.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request16.QueryStringParameters.Add("FORM", "MONITR", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://www.bing.com/fd/ls/GLinkPing.aspx");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            request17.QueryStringParameters.Add("IG", "BB23759912D042EA9449A89347BB9189", false, false);
            request17.QueryStringParameters.Add("", "", false, false);
            request17.QueryStringParameters.Add("ID", "SERP,5137.1", false, false);
            request17.QueryStringParameters.Add("url", "https%3A%2F%2Fwww.hdfcbank.com%2F", false, false);
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://www.bing.com/fd/ls/lsp.aspx");
            request18.ThinkTime = 12;
            request18.Method = "POST";
            request18.Headers.Add(new WebTestRequestHeader("Referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02"));
            StringHttpBody request18Body = new StringHttpBody();
            request18Body.ContentType = "text/xml";
            request18Body.InsertByteOrderMark = false;
            request18Body.BodyString = @"<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>BB23759912D042EA9449A89347BB9189</IG><TS>1551796973716</TS><D><![CDATA[[{""T"":""CI.BoxModel"",""FID"":""CI"",""Name"":""v2.8"",""SV"":""4"",""P"":{""C"":18,""N"":2,""I"":""51d"",""S"":""C+BD+U"",""M"":""V+L+M+MT+E+N+C+K+BD"",""T"":4732,""K"":""3n8+1hs+ipv6test%2Ftest+1yr+apc%2Ftrans.gif+3hy+3is+2z0+pointermove"",""F"":1},""M"":""14y+2z0+aa+3n8+1y+2+0+1+0+7b+1"",""E"":""@1p/l/X/26/"",""N"":""1h8/1r//@d/ls%2Flsp.aspx/@l/48/@e/@1q/-1/@1q/1ht/1lf/1lh+1od/1s//91040ad32f092496cbbc2c1d2a83db9c.clo.footprintdns.com/@1t/@g/0/@e/-1/-1/-1/-1/-1/-1+1yg/1t//www2.bing.com/@1r/@j/49/@e/-1/-1/-1/-1/-1/22q+1yl/1u//@d/@1r/@l/4r/@e/@1s/-1/@1s/@1s/23c/23d+385/1v//0fe764ef5a21378df3b71bfa563d4f8a.clo.footprintdns.com/@1t/@g/am/@e/-1/-1/-1/-1/-1/@1v+3hv/1w//@d/ls%2FGLinkPing.aspx/@g/3j/@e/@1u/-1/@1u/@1u/-1/3lf+@1v/1x//20cdead37b92e844601ff1e6e955730d.clo.footprintdns.com/@1t/@g/0/@e/-1/-1/-1/-1/-1/-1"",""C"":""@1w//@1x/mouse/-1/3/5b/0+2z3/////e/5e/+2zf/////m/5m/+2zw/////13/5r/+303/////1d/5t/+30i/////1o/5w/+30q/////22/67/+317/////2g/69/+31n/8////2u/6d/+327/////3e/6e/+32l/////3s//+32z/////4b//+331/////4n//+33p/////51/6b/+34k/////5j/65/+35h/////5u/61/+36r/////64/5s/+37o/////6d/5l/+39a/////6m/5d/+3ht//pointerdown//0/6t/59/1+3ju//pointerup/////0+3jx//click/////"",""BD"":""@1w/@1x/1551796973""}]]]></D></E></Events><STS>1551796973716</STS></ClientInstRequest>";
            request18.Body = request18Body;
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://8328018.fls.doubleclick.net/activityi;src=8328018;type=testr0;cat=hdfcb0;" +
                    "ord=5959044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A//www.hdfcb" +
                    "ank.com/;~oref=https%3A//www.hdfcbank.com/");
            request19.ExpectedResponseUrl = "https://8328018.fls.doubleclick.net/activityi;src=8328018;type=testr0;cat=hdfcb0;" +
                "ord=5959044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A%2F%2Fwww.h" +
                "dfcbank.com%2F;~oref=https%3A%2F%2Fwww.hdfcbank.com%2F?";
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request19.QueryStringParameters.Add("", "", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://adservice.google.com/ddm/fls/i/src=8328018;type=testr0;cat=hdfcb0;ord=595" +
                    "9044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A//www.hdfcbank.com" +
                    "/;_dc_1=1;~oref=https%3A//www.hdfcbank.com/");
            request20.ExpectedResponseUrl = "https://adservice.google.com/ddm/fls/i/src=8328018;type=testr0;cat=hdfcb0;ord=595" +
                "9044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A%2F%2Fwww.hdfcbank" +
                ".com%2F;_dc_1=1;~oref=https%3A%2F%2Fwww.hdfcbank.com%2F";
            request20.Headers.Add(new WebTestRequestHeader("Referer", "https://8328018.fls.doubleclick.net/activityi;src=8328018;type=testr0;cat=hdfcb0;" +
                        "ord=5959044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A%2F%2Fwww.h" +
                        "dfcbank.com%2F;~oref=https%3A%2F%2Fwww.hdfcbank.com%2F?"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://adservice.google.co.in/ddm/fls/i/src=8328018;type=testr0;cat=hdfcb0;ord=5" +
                    "959044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A//www.hdfcbank.c" +
                    "om/;_dc_1=3;~oref=https%3A//www.hdfcbank.com/");
            request21.ExpectedResponseUrl = "https://adservice.google.co.in/ddm/fls/i/src=8328018;type=testr0;cat=hdfcb0;ord=5" +
                "959044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A%2F%2Fwww.hdfcba" +
                "nk.com%2F;_dc_1=3;~oref=https%3A%2F%2Fwww.hdfcbank.com%2F";
            request21.Headers.Add(new WebTestRequestHeader("Referer", "https://adservice.google.com/ddm/fls/i/src=8328018;type=testr0;cat=hdfcb0;ord=595" +
                        "9044307031;gtm=2wg241;auiddc=1268362540.1551796986;u6=https%3A%2F%2Fwww.hdfcbank" +
                        ".com%2F;_dc_1=1;~oref=https%3A%2F%2Fwww.hdfcbank.com%2F"));
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://offers.smartbuy.hdfcbank.com/");
            request22.ThinkTime = 12;
            request22.QueryStringParameters.Add("src", "hp_nav", false, false);
            request22.QueryStringParameters.Add("_ga", "2.41605479.497966783.1551796986-252543771.1551796986", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("http://offers.smartbuy.hdfcbank.com/");
            request23.QueryStringParameters.Add("src", "hp_nav", false, false);
            request23.QueryStringParameters.Add("_ga", "2.41605479.497966783.1551796986-252543771.1551796986", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://dpm.demdex.net/id");
            request24.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded"));
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request24.QueryStringParameters.Add("d_visid_ver", "3.4.0", false, false);
            request24.QueryStringParameters.Add("d_fieldgroup", "MC", false, false);
            request24.QueryStringParameters.Add("d_rtbd", "json", false, false);
            request24.QueryStringParameters.Add("d_ver", "2", false, false);
            request24.QueryStringParameters.Add("d_orgid", "3817033753EE89720A490D4D%40AdobeOrg", false, false);
            request24.QueryStringParameters.Add("d_nsid", "0", false, false);
            request24.QueryStringParameters.Add("ts", "1551796984633", false, false);
            FormPostHttpBody request24Body = new FormPostHttpBody();
            request24.Body = request24Body;
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://hdfcbank.tt.omtrdc.net/m2/hdfcbank/mbox/json");
            request25.ThinkTime = 2;
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request25.QueryStringParameters.Add("mbox", "target-global-mbox", false, false);
            request25.QueryStringParameters.Add("mboxSession", "e2f9988530ed479595730c80e2d4b629", false, false);
            request25.QueryStringParameters.Add("mboxPC", "", false, false);
            request25.QueryStringParameters.Add("mboxPage", "4a7f1eeedbdf463c892ed0b10e9e8c0e", false, false);
            request25.QueryStringParameters.Add("mboxRid", "79a4da716ae54d5ab2b601f5030ad0fa", false, false);
            request25.QueryStringParameters.Add("mboxVersion", "1.6.0", false, false);
            request25.QueryStringParameters.Add("mboxCount", "1", false, false);
            request25.QueryStringParameters.Add("mboxTime", "1551816784764", false, false);
            request25.QueryStringParameters.Add("mboxHost", "www.hdfcbank.com", false, false);
            request25.QueryStringParameters.Add("mboxURL", "https%3A%2F%2Fwww.hdfcbank.com%2F", false, false);
            request25.QueryStringParameters.Add("mboxReferrer", "http%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dwww.hdfcbank.com%26src%3DIE-SearchBox%26" +
                    "FORM%3DIESR02", false, false);
            request25.QueryStringParameters.Add("browserHeight", "537", false, false);
            request25.QueryStringParameters.Add("browserWidth", "575", false, false);
            request25.QueryStringParameters.Add("browserTimeOffset", "330", false, false);
            request25.QueryStringParameters.Add("screenHeight", "768", false, false);
            request25.QueryStringParameters.Add("screenWidth", "1366", false, false);
            request25.QueryStringParameters.Add("colorDepth", "24", false, false);
            request25.QueryStringParameters.Add("devicePixelRatio", "1", false, false);
            request25.QueryStringParameters.Add("screenOrientation", "landscape", false, false);
            request25.QueryStringParameters.Add("webGLRenderer", "Microsoft%20Basic%20Render%20Driver", false, false);
            request25.QueryStringParameters.Add("entity.id", "", false, false);
            request25.QueryStringParameters.Add("Poduct_side", "", false, false);
            request25.QueryStringParameters.Add("Product_page", "", false, false);
            request25.QueryStringParameters.Add("mboxMCSDID", "10752A0A3F696BFB-6F9FB18209EA5F63", false, false);
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://hdfcbank.demdex.net/dest5.html");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request26.QueryStringParameters.Add("d_nsid", "0", false, false);
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://www.google-analytics.com/r/collect");
            request27.ThinkTime = 1;
            request27.ExpectedResponseUrl = "https://www.google.co.in/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-23795917-13&" +
                "cid=252543771.1551796986&jid=929941645&_v=j73&z=1365180885&slf_rd=1&random=16833" +
                "17034";
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request27.QueryStringParameters.Add("v", "1", false, false);
            request27.QueryStringParameters.Add("_v", "j73", false, false);
            request27.QueryStringParameters.Add("a", "89641333", false, false);
            request27.QueryStringParameters.Add("t", "event", false, false);
            request27.QueryStringParameters.Add("ni", "0", false, false);
            request27.QueryStringParameters.Add("_s", "1", false, false);
            request27.QueryStringParameters.Add("dl", "https%3A%2F%2Fwww.hdfcbank.com%2F", false, false);
            request27.QueryStringParameters.Add("dr", "http%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dwww.hdfcbank.com%26src%3DIE-SearchBox%26" +
                    "FORM%3DIESR02", false, false);
            request27.QueryStringParameters.Add("ul", "en-us", false, false);
            request27.QueryStringParameters.Add("de", "utf-8", false, false);
            request27.QueryStringParameters.Add("dt", "HDFC%20Bank%3A%20Personal%20Banking%20Services", false, false);
            request27.QueryStringParameters.Add("sd", "24-bit", false, false);
            request27.QueryStringParameters.Add("sr", "1366x768", false, false);
            request27.QueryStringParameters.Add("vp", "558x520", false, false);
            request27.QueryStringParameters.Add("je", "1", false, false);
            request27.QueryStringParameters.Add("fl", "18.0%20r0", false, false);
            request27.QueryStringParameters.Add("ec", "Top%20Navigation%20Menu%20-%20Main%20Website", false, false);
            request27.QueryStringParameters.Add("ea", "undefined", false, false);
            request27.QueryStringParameters.Add("el", "%2F", false, false);
            request27.QueryStringParameters.Add("_u", "aGDACEQAB~", false, false);
            request27.QueryStringParameters.Add("jid", "929941645", false, false);
            request27.QueryStringParameters.Add("gjid", "1516347630", false, false);
            request27.QueryStringParameters.Add("cid", "252543771.1551796986", false, false);
            request27.QueryStringParameters.Add("tid", "UA-23795917-13", false, false);
            request27.QueryStringParameters.Add("_gid", "497966783.1551796986", false, false);
            request27.QueryStringParameters.Add("_r", "1", false, false);
            request27.QueryStringParameters.Add("gtm", "2wg241K7RG59", false, false);
            request27.QueryStringParameters.Add("z", "1365180885", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1056451846/");
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request28.QueryStringParameters.Add("random", "1551796999104", false, false);
            request28.QueryStringParameters.Add("cv", "9", false, false);
            request28.QueryStringParameters.Add("fst", "1551796999104", false, false);
            request28.QueryStringParameters.Add("num", "1", false, false);
            request28.QueryStringParameters.Add("guid", "ON", false, false);
            request28.QueryStringParameters.Add("resp", "GooglemKTybQhCsO", false, false);
            request28.QueryStringParameters.Add("eid", "376635471", false, false);
            request28.QueryStringParameters.Add("u_h", "768", false, false);
            request28.QueryStringParameters.Add("u_w", "1366", false, false);
            request28.QueryStringParameters.Add("u_ah", "728", false, false);
            request28.QueryStringParameters.Add("u_aw", "1366", false, false);
            request28.QueryStringParameters.Add("u_cd", "24", false, false);
            request28.QueryStringParameters.Add("u_his", "2", false, false);
            request28.QueryStringParameters.Add("u_tz", "330", false, false);
            request28.QueryStringParameters.Add("u_java", "true", false, false);
            request28.QueryStringParameters.Add("u_nplug", "1", false, false);
            request28.QueryStringParameters.Add("u_nmime", "2", false, false);
            request28.QueryStringParameters.Add("gtm", "2wg241", false, false);
            request28.QueryStringParameters.Add("frm", "0", false, false);
            request28.QueryStringParameters.Add("url", "https%3A%2F%2Fwww.hdfcbank.com%2F", false, false);
            request28.QueryStringParameters.Add("ref", "http%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dwww.hdfcbank.com%26src%3DIE-SearchBox%26" +
                    "FORM%3DIESR02", false, false);
            request28.QueryStringParameters.Add("tiba", "HDFC%20Bank%3A%20Personal%20Banking%20Services", false, false);
            request28.QueryStringParameters.Add("async", "1", false, false);
            request28.QueryStringParameters.Add("rfmt", "3", false, false);
            request28.QueryStringParameters.Add("fmt", "4", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1064886967/");
            request29.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request29.QueryStringParameters.Add("random", "1551796999130", false, false);
            request29.QueryStringParameters.Add("cv", "9", false, false);
            request29.QueryStringParameters.Add("fst", "1551796999130", false, false);
            request29.QueryStringParameters.Add("num", "1", false, false);
            request29.QueryStringParameters.Add("guid", "ON", false, false);
            request29.QueryStringParameters.Add("resp", "GooglemKTybQhCsO", false, false);
            request29.QueryStringParameters.Add("eid", "376635471", false, false);
            request29.QueryStringParameters.Add("u_h", "768", false, false);
            request29.QueryStringParameters.Add("u_w", "1366", false, false);
            request29.QueryStringParameters.Add("u_ah", "728", false, false);
            request29.QueryStringParameters.Add("u_aw", "1366", false, false);
            request29.QueryStringParameters.Add("u_cd", "24", false, false);
            request29.QueryStringParameters.Add("u_his", "2", false, false);
            request29.QueryStringParameters.Add("u_tz", "330", false, false);
            request29.QueryStringParameters.Add("u_java", "true", false, false);
            request29.QueryStringParameters.Add("u_nplug", "1", false, false);
            request29.QueryStringParameters.Add("u_nmime", "2", false, false);
            request29.QueryStringParameters.Add("gtm", "2wg241", false, false);
            request29.QueryStringParameters.Add("frm", "0", false, false);
            request29.QueryStringParameters.Add("url", "https%3A%2F%2Fwww.hdfcbank.com%2F", false, false);
            request29.QueryStringParameters.Add("ref", "http%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dwww.hdfcbank.com%26src%3DIE-SearchBox%26" +
                    "FORM%3DIESR02", false, false);
            request29.QueryStringParameters.Add("tiba", "HDFC%20Bank%3A%20Personal%20Banking%20Services", false, false);
            request29.QueryStringParameters.Add("async", "1", false, false);
            request29.QueryStringParameters.Add("rfmt", "3", false, false);
            request29.QueryStringParameters.Add("fmt", "4", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://connect.facebook.net/signals/config/353555438406160");
            request30.ThinkTime = 9;
            request30.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request30.QueryStringParameters.Add("v", "2.8.42", false, false);
            request30.QueryStringParameters.Add("r", "stable", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://offers.smartbuy.hdfcbank.com/ram/checkcaptcha/captcha");
            request31.Headers.Add(new WebTestRequestHeader("Referer", "http://offers.smartbuy.hdfcbank.com/?src=hp_nav&_ga=2.41605479.497966783.15517969" +
                        "86-252543771.1551796986"));
            request31.QueryStringParameters.Add("rand", "1030281168", false, false);
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://www.hdfcbank.com/assets/fonts/opensans-semibold-webfont.eot");
            request32.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request32.QueryStringParameters.Add("", "", false, false);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://www.hdfcbank.com/assets/fonts/opensans-regular-webfont.eot");
            request33.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request33.QueryStringParameters.Add("", "", false, false);
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://www.hdfcbank.com/assets/fonts/helveticabold-webfont.eot");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request34.QueryStringParameters.Add("", "", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://www.hdfcbank.com/assets/fonts/OpenSans-Semibold.eot");
            request35.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://www.hdfcbank.com/assets/fonts/OpenSans.eot");
            request36.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("https://hdfcbank.demdex.net/event");
            request37.ThinkTime = 1;
            request37.Method = "POST";
            request37.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request37.QueryStringParameters.Add("_ts", "1551796999634", false, false);
            FormPostHttpBody request37Body = new FormPostHttpBody();
            request37Body.FormPostParameters.Add("d_mid", "35778183650259235682535538252077900943");
            request37Body.FormPostParameters.Add("d_nsid", "0");
            request37Body.FormPostParameters.Add("d_ld", "_ts=1551796999632");
            request37Body.FormPostParameters.Add("d_rtbd", "json");
            request37Body.FormPostParameters.Add("d_jsonv", "1");
            request37Body.FormPostParameters.Add("d_dst", "1");
            request37Body.FormPostParameters.Add("c_hash", "");
            request37Body.FormPostParameters.Add("c_host", "www.hdfcbank.com");
            request37Body.FormPostParameters.Add("c_hostname", "www.hdfcbank.com");
            request37Body.FormPostParameters.Add("c_pathname", "");
            request37Body.FormPostParameters.Add("c_protocol", "https:");
            request37Body.FormPostParameters.Add("d_URL", "https://www.hdfcbank.com/");
            request37Body.FormPostParameters.Add("d_referer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02");
            request37Body.FormPostParameters.Add("c_.event", "gtm.js|gtm.click|gtm.linkClick");
            request37Body.FormPostParameters.Add("c_.eventcallback", "function(){}");
            request37Body.FormPostParameters.Add("c_.eventtimeout", "2000");
            request37Body.FormPostParameters.Add("c_name", "gtm12");
            request37Body.FormPostParameters.Add("c_trackingId", "UA-23795917-13");
            request37Body.FormPostParameters.Add("c_cookieName", "_ga");
            request37Body.FormPostParameters.Add("c_cookieDomain", "hdfcbank.com");
            request37Body.FormPostParameters.Add("c_cookiePath", "/");
            request37Body.FormPostParameters.Add("c_cookieExpires", "63072000");
            request37Body.FormPostParameters.Add("c_cookieUpdate", "true");
            request37Body.FormPostParameters.Add("c_legacyHistoryImport", "true");
            request37Body.FormPostParameters.Add("c_allowLinker", "true");
            request37Body.FormPostParameters.Add("c_allowAnchor", "true");
            request37Body.FormPostParameters.Add("c_sampleRate", "100");
            request37Body.FormPostParameters.Add("c_siteSpeedSampleRate", "1");
            request37Body.FormPostParameters.Add("c_alwaysSendReferrer", "false");
            request37Body.FormPostParameters.Add("c_storage", "cookie");
            request37Body.FormPostParameters.Add("c_storeGac", "true");
            request37Body.FormPostParameters.Add("c_apiVersion", "1");
            request37Body.FormPostParameters.Add("c_clientVersion", "j73");
            request37Body.FormPostParameters.Add("c_referrer", "http://www.bing.com/search?q=www.hdfcbank.com&src=IE-SearchBox&FORM=IESR02");
            request37Body.FormPostParameters.Add("c_location", "https://www.hdfcbank.com/");
            request37Body.FormPostParameters.Add("c_screenResolution", "1366x768");
            request37Body.FormPostParameters.Add("c_screenColors", "24-bit");
            request37Body.FormPostParameters.Add("c_viewportSize", "558x520");
            request37Body.FormPostParameters.Add("c_flashVersion", "18.0 r0");
            request37Body.FormPostParameters.Add("c_encoding", "utf-8");
            request37Body.FormPostParameters.Add("c_javaEnabled", "true");
            request37Body.FormPostParameters.Add("c_language", "en-us");
            request37Body.FormPostParameters.Add("c_clientId", "252543771.1551796986");
            request37Body.FormPostParameters.Add("c_adSenseId", "89641333");
            request37Body.FormPostParameters.Add("c_dimension4", "https:");
            request37Body.FormPostParameters.Add("c_dimension17", "Not Exposed to Start Doing");
            request37Body.FormPostParameters.Add("c_dimension18", "true");
            request37Body.FormPostParameters.Add("c_page", "/");
            request37Body.FormPostParameters.Add("c_dcLoaded", "true");
            request37.Body = request37Body;
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://hbchat.senseforth.com/HDFC_Chat/assets/fonts/OpenSans-Regular.eot");
            request38.Headers.Add(new WebTestRequestHeader("Referer", "https://www.hdfcbank.com/"));
            request38.QueryStringParameters.Add("", "", false, false);
            yield return request38;
            request38 = null;
        }
    }
}
